spring.application.name=lutetiaWebshop
spring.datasource.url=jdbc:postgresql://localhost:5432/lutetiashop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=20000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop
server.error.include-message=always
server.port=8080
server.servlet.context-path=/api
jwt.secret=supersecretduckspassgwordtokens11**
jwt.expiration=3600000